spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Sell12345!
    url: jdbc:mysql://XXXX/waimai?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true