spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Sell12345!
    url: jdbc:mysql://172.16.247.128/waimai?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true